title: Bienvenidos al Mañana
author: Heraldo del mañana
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  ¿Por que no dejar para mañana lo que puedes hacer hoy?
  ¿Quieres la paz? Allí es adonde voy, 
  por 100 euros diarios yo te la doy, 
  el hacerdor de sonrisas es lo que soy. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
_config.yml: minima 
theme: minima
